version: "3.0"
services:
  db-postgres:
    image: postgres:alpine
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker

  db-mongo:
    image: mongo
    ports:
    - "21017:21017"

  db-redis:
    image:  redis:alpine
    ports:
    - "6379:6379"

